name: CI

on: 
  push:
    branches: 
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches: 
      - '*'

jobs:  
  build_manifests:  
    runs-on: ubuntu-18.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # login-server: # default is https://index.docker.io/v1/ 
      
      - name: Build and Push Manifests
        env:
          CONTAINER_MANIFEST_TAG: ${{ steps.extract_branch.outputs.branch }}
          if: github.event.pull_request.labels.name != ''
          CONTINAER_MANIFEST_TAG: pr${{ github.event.pull_request.labels.name }}
        run: |          
          sed -i 's/}}/}}, "experimental": "enabled"/g' "${DOCKER_CONFIG}/config.json"
          
          docker -D manifest create \
              "ssbkang/portainer:$CONTINAER_MANIFEST_TAG" \
              "ssbkang/portainer:$CONTINAER_MANIFEST_TAG-linux-amd64" \
              "ssbkang/portainer:$CONTINAER_MANIFEST_TAG-windows1809-amd64"

          docker -D manifest push "ssbkang/portainer:$CONTINAER_MANIFEST_TAG"  
