name: CI

on: 
  push:
    branches: 
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1.0.0
        with:
          version: 1.13.1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - run: |
          yarn install
          yarn publish
