name: CI

on: 
  push:
    branches: 
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches: 
      - '*'

jobs:
  build_artefacts:
    strategy:
      matrix:
        os: [linux, windows]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1.0.0
        with:
          version: 1.13.1
      - name: Setup NodeJS and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '11.15.0'
      - name: Build Linux & Windows Portainer Binaries
        run: |
          yarn install          
          grunt release:${{ matrix.os }}:amd64 --gruntfile gruntfile.js
          mv dist dist_${{ matrix.os }}
          ls -la dist_${{ matrix.os }}
