name: CI

on: 
  push:
    branches: 
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches: 
      - '*'

env:  
  CONTINAER_IMAGE_TAG: pr${{ github.event.pull_request.labels.name }}

jobs:  
  build_manifests:  
    runs-on: ubuntu-18.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # login-server: # default is https://index.docker.io/v1/ 
      
      - name: Build and Push Manifests
        env:
          if: github.event.pull_request.labels.name == ''
          CONTAINER_IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
        run: |
          sed -i 's/}}/}}, "experimental": "enabled"/g' "${DOCKER_CONFIG}/config.json"
          
          docker -D manifest create \
              "ssbkang/portainer:$CONTAINER_IMAGE_TAG" \
              "ssbkang/portainer:$CONTAINER_IMAGE_TAG-linux-amd64" \
              "ssbkang/portainer:$CONTAINER_IMAGE_TAG-windows1809-amd64"

          docker -D manifest push "ssbkang/portainer:$CONTAINER_IMAGE_TAG"  
